### ISSUE TITLE
How to connect via ssh?

### ISSUE THREAD

**Issue by sschuett** [Michaelcgn/graylog_vagrant_demo#1]
Hi Michael,

thank you for your execellent speach on SEO Day 2015 last week! I am very keen on testing this solution. Could you please complete the howto section on how to get on the vagrantbox via ssh?

Thanks,

Stefan

**Comment by sschuett** [comment]
Oh, I have just found out myself:
"vagrant ssh" does the trick...

**Comment by Michaelcgn** [comment]
I'm using WinScp to work on the VM. And with WinSCP i connect via Putty to the machine.
The credentials are:
host: localhost
Port: 2222
User: vagrant
Password: vagrant
And you need the "insecure_private_key" from the vagrant folder. It's a little bit tricky, because you have to transform the key for WinScp with PuttyGen. (It's my normal dev-setup ;) )

P.s.: There was an error in the vagrant file... the last commit is right.
